### ISSUE TITLE
Shift enter not working

### ISSUE THREAD

**Issue by thekhan314** [learn-co-curriculum/dsc-standard-normal-distribution-lab#1]
Pressing shift enter does not seem to be working. Its neither displaying the plot, nor showing an error message. In the square brackets for the cell, instead of showing the execution order it switches to showing the asterisk(*)
![image](https://user-images.githubusercontent.com/51972123/65401258-88b16d80-dd8c-11e9-9041-9a845da6097b.png)

**Comment by bpurdy-ds** [comment]
Since 2019 this lab has been modified and this is no longer an issue, but while I was here, I changed `distplot` to `displot` to remove the deprecation error.
